---
title: "Plot distributions"
author: "MochiBear.Hei"
date: "04.06.2025"
format:
  html:
    toc: true
    toc-location: left
    embed-resources: true
    page-layout: full
    html-math-method: katex
editor: source
---

```{css, echo = F}
body{
  font-family: Helvetica;
  font-size: 16pt;
  max-width: 1000px;
  margin: auto;
  margin-left:310px;
}
pre{
  font-size: 14px;
}
/* Headers */
h1{
    font-size: 24pt;
  }
h1,h2{
    font-size: 20pt;
  }
h3,h4,h5,h6{
  font-size: 18pt;
}
#TOC {
  position: fixed;
  left: 0;
  top: 0;
  width: 300px;
  height: 100%;
  overflow:auto;
}
```

```{r setup,suppressPackageStartupMessages= TRUE}
#| include: false
#| message: false
#| warning: false
#| results: hide
knitr::opts_chunk$set(echo = TRUE, dpi = 300)

# Data manipulation
library(dplyr)
library(tidyr)

#models
library(caret)
library(xgboost)

# Plotting
library(ggplot2)
library(viridis)      

# Utilities
library(knitr)
```

Loads MRI and externalizing symptom scores (BPM & CBCL), handles missing data, and visualizes youth- and parent-reported externalizing symptom T-score distributions using overlaid histograms and density plots.

# Load
## ID list
```{r}
##list of people to include in analysis subids.csv
subids <- read.csv("/Users/maggieheimvik/Desktop/GitHub/masters_thesis/Data/ocd/subids.csv") 
```

## MRI
```{r}
mri <- read.csv("/Users/maggieheimvik/Desktop/GitHub/masters_thesis/Data/ocd/mri.csv") %>%
  select (-smri_vol_scs_lesionlh, -smri_vol_scs_lesionrh, -smri_vol_scs_intracranialv) #removed these columns because they have 4897 NA each; should i remove , mrisdp_604 total cortical volume?


full_dat <- mri[mri$src_subject_id %in% subids$src_subject_id, ]
```

## BPM
```{r}
bpm <- read.csv("/Users/maggieheimvik/Desktop/GitHub/masters_thesis/Data/core/mental-health/mh_y_bpm.csv") %>%
  filter(eventname == "2_year_follow_up_y_arm_1") %>%
  select(src_subject_id, bpm_y_scr_external_t) %>%
  distinct(src_subject_id, .keep_all = TRUE)  #remove duplicates


# merge
full_dat <- inner_join(full_dat, bpm, by = "src_subject_id")
```
## CBCL
```{r}
cbcl <- read.csv("/Users/maggieheimvik/Desktop/LCBC/Data/ABCD/core/mental-health/mh_p_cbcl.csv") %>%
  filter(eventname == "2_year_follow_up_y_arm_1") %>%
  select(src_subject_id, cbcl_scr_syn_external_t) %>%
  distinct(src_subject_id, .keep_all = TRUE) 


# merge
full_dat <- inner_join(full_dat, cbcl, by = "src_subject_id")
```

# Handle NA
```{r}
na_counts <- colSums(is.na(full_dat))
na_counts[na_counts > 0]  # print only columns with NA values


full_dat <- full_dat %>%
  mutate(across(
    c(mrisdp_508, mrisdp_527, mrisdp_582, mrisdp_601, mrisdp_602, mrisdp_603, mrisdp_604),
    ~ ifelse(is.na(.), mean(., na.rm = TRUE), .)
  )) %>%
  filter(!is.na(bpm_y_scr_external_t))

```


#plot all together
```{r}

# Reshape data to long format
long_dat <- full_dat %>%
  select( bpm_y_scr_external_t, cbcl_scr_syn_external_t) %>%
  pivot_longer(cols = everything(), names_to = "variable", values_to = "value") %>%
  mutate(variable = recode(variable,
    "bpm_y_scr_external_t"    = "Youth-Reported",
    "cbcl_scr_syn_external_t" = "Parent-Reported"
  ))

# Function to calculate density and get max y-value
calculate_density_and_max <- function(data) {
  dens <- density(data$value, na.rm = TRUE)
  return(max(dens$y))
}

# Calculate global max density for fixed y-axis
max_density <- long_dat %>%
  group_by(variable) %>%
  summarise(max_density = calculate_density_and_max(cur_data())) %>%
  summarise(global_max = max(max_density)) %>%
  pull(global_max)

p <- ggplot(long_dat, aes(x = value, fill = variable)) +
  geom_histogram(aes(y = ..density..), bins = 30, color = "black", alpha = 0.3) +
  geom_density(alpha = 0.6) +
  facet_wrap(~ variable, scales = "fixed") +
  labs(
    title = "Distribution of externalizing Symptom Scores",
    x = "T-Score",
    y = "Density"
  ) +
  scale_fill_manual(values = c("#2E8B57", "#800080")) +
  theme_classic(base_size = 14) +
  theme(
    legend.position = "none",
    strip.text = element_text(face = "bold")
  )
p
ggsave("t_score_distribution.png", plot = p, width = 8, height = 5)


```